import type { Metadata } from "next";
import { Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | Calcoder",
  description: "Calcoder terms of service. Learn about the conditions for using our free online tools and calculators.",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 sm:px-6 lg:px-8 max-w-3xl">
      <div className="text-center mb-12">
        <div className="inline-flex items-center justify-center p-4 bg-primary/10 text-primary rounded-full mb-6">
          <Scale className="w-10 h-10" />
        </div>
        <h1 className="text-4xl font-extrabold tracking-tight mb-4">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: May 2026</p>
      </div>

      <div className="glass-panel p-8 sm:p-10 rounded-2xl prose prose-slate max-w-none">
        <h2>Acceptance of Terms</h2>
        <p>
          By accessing or using Calcoder (&quot;the Website&quot;), you agree to be bound by these Terms of Service. 
          If you do not agree, please do not use the Website.
        </p>

        <h2>Use of Tools</h2>
        <p>
          All tools and calculators on Calcoder are provided <strong>&quot;as is&quot;</strong> and <strong>&quot;as available&quot;</strong> 
          without any warranty, express or implied.
        </p>
        <ul>
          <li>Tools are intended for general informational and educational purposes only.</li>
          <li>Financial calculators provide estimates only and should not be considered professional financial advice.</li>
          <li>You are solely responsible for any decisions made based on the tools&apos; output.</li>
          <li>Media tools process files client-side in your browser. We do not store or access your uploaded files.</li>
        </ul>

        <h2>No Financial Advice</h2>
        <p>
          Calculators related to finance (SIP, EMI, ROI, taxes, etc.) provide approximate results for 
          reference only. They do not constitute financial, legal, or tax advice. Consult a qualified 
          professional for financial decisions.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the tools for any unlawful purpose</li>
          <li>Attempt to disrupt, overload, or damage the Website</li>
          <li>Scrape, crawl, or systematically extract data without permission</li>
          <li>Upload malicious files or attempt to abuse the media processing tools</li>
          <li>Use the Website in a way that could harm other users or third parties</li>
        </ul>

        <h2>Intellectual Property</h2>
        <p>
          The Calcoder name, logo, design, and code are our intellectual property. The tool outputs 
          generated by users belong to the respective users. You may not copy, reproduce, or 
          redistribute the Website&apos;s design or substantial portions of its content without permission.
        </p>

        <h2>Third-Party Services</h2>
        <p>
          The Website displays advertisements via Google AdSense. We are not responsible for the 
          content of these advertisements or the practices of third-party advertisers.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by applicable law, Calcoder and its operators shall not 
          be liable for any indirect, incidental, special, consequential, or punitive damages, 
          including but not limited to loss of profits, data, or use, arising out of or in connection 
          with the Website or its tools.
        </p>

        <h2>Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use of the Website 
          after changes constitutes acceptance of the new terms.
        </p>

        <h2>Contact</h2>
        <p>
          For questions about these terms, please <a href="/contact" className="text-primary">contact us</a>.
        </p>
      </div>
    </div>
  );
}
